// In-Memory Database Store for Kisan Setu Express Backend

export const MANDIS = [
  {
    id: "mandi-1",
    name: "Karnal Central MSP Mandi",
    district: "Karnal",
    state: "Haryana",
    distanceKm: 4.2,
    maxCapacityPerDay: 150,
    currentBooked: 112,
    countersActive: 4,
    avgProcessingTimeMins: 12,
    moistureLimitPct: 14,
    status: "OPEN",
    lat: 29.6857,
    lng: 76.9905,
  },
  {
    id: "mandi-2",
    name: "Ludhiana Grain Hub",
    district: "Ludhiana",
    state: "Punjab",
    distanceKm: 8.7,
    maxCapacityPerDay: 200,
    currentBooked: 195,
    countersActive: 6,
    avgProcessingTimeMins: 10,
    moistureLimitPct: 12,
    status: "HEAVY_LOAD",
    lat: 30.9010,
    lng: 75.8573,
  },
  {
    id: "mandi-3",
    name: "Kurukshetra Agri Market",
    district: "Kurukshetra",
    state: "Haryana",
    distanceKm: 12.1,
    maxCapacityPerDay: 120,
    currentBooked: 45,
    countersActive: 3,
    avgProcessingTimeMins: 15,
    moistureLimitPct: 14,
    status: "SMOOTH",
    lat: 29.9695,
    lng: 76.8783,
  },
  {
    id: "mandi-4",
    name: "Indore MSP Procurement Centre",
    district: "Indore",
    state: "Madhya Pradesh",
    distanceKm: 18.5,
    maxCapacityPerDay: 180,
    currentBooked: 90,
    countersActive: 5,
    avgProcessingTimeMins: 11,
    moistureLimitPct: 13,
    status: "OPEN",
    lat: 22.7196,
    lng: 75.8577,
  }
];

export const CROPS = [
  { id: "wheat", name: "Wheat (गेहूँ / ਕਣਕ)", mspPerQuintal: 2275, unit: "Quintal", maxPerFarmer: 150, icon: "🌾" },
  { id: "paddy", name: "Paddy / Rice (धान / ਝੋਨਾ)", mspPerQuintal: 2300, unit: "Quintal", maxPerFarmer: 200, icon: "🌾" },
  { id: "chana", name: "Gram / Chana (चना / ਛੋਲੇ)", mspPerQuintal: 5440, unit: "Quintal", maxPerFarmer: 80, icon: "🌱" },
  { id: "mustard", name: "Mustard / Sarson (सरसों / ਸਰ੍ਹੋਂ)", mspPerQuintal: 5650, unit: "Quintal", maxPerFarmer: 60, icon: "🌼" },
  { id: "maize", name: "Maize / Makka (मक्का / ਮੱਕੀ)", mspPerQuintal: 2090, unit: "Quintal", maxPerFarmer: 100, icon: "🌽" },
];

export let tokensState = [
  {
    id: "KS-2026-451",
    tokenNumber: 45,
    farmerName: "Ramesh Kumar",
    farmerMobile: "9876543210",
    farmerId: "PMK-HAR-88421",
    cropId: "wheat",
    cropName: "Wheat",
    quantityQuintal: 40,
    mandiId: "mandi-1",
    mandiName: "Karnal Central MSP Mandi",
    slotDate: new Date().toISOString().split("T")[0],
    slotTimeWindow: "09:00 AM - 10:30 AM",
    counterAssigned: "Counter 2",
    status: "PAYMENT_DISPATCHED",
    checkInTime: "09:12 AM",
    weighmentData: { grossKg: 4200, tareKg: 200, netQuintals: 40, moisturePct: 11.5, grade: "Grade A", totalPayoutRs: 91000 },
    pfmsTxnId: "PFMS-99482019482",
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: "KS-2026-452",
    tokenNumber: 46,
    farmerName: "Gurpreet Singh",
    farmerMobile: "9812345678",
    farmerId: "PMK-PB-12903",
    cropId: "wheat",
    cropName: "Wheat",
    quantityQuintal: 65,
    mandiId: "mandi-1",
    mandiName: "Karnal Central MSP Mandi",
    slotDate: new Date().toISOString().split("T")[0],
    slotTimeWindow: "10:30 AM - 12:00 PM",
    counterAssigned: "Counter 1",
    status: "WEIGHMENT_DONE",
    checkInTime: "10:25 AM",
    weighmentData: { grossKg: 6800, tareKg: 300, netQuintals: 65, moisturePct: 12.8, grade: "FAQ (Fair Average Quality)", totalPayoutRs: 147875 },
    pfmsTxnId: null,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "KS-2026-453",
    tokenNumber: 47,
    farmerName: "Sukhwinder Kaur",
    farmerMobile: "9789012345",
    farmerId: "PMK-PB-99381",
    cropId: "paddy",
    cropName: "Paddy",
    quantityQuintal: 50,
    mandiId: "mandi-1",
    mandiName: "Karnal Central MSP Mandi",
    slotDate: new Date().toISOString().split("T")[0],
    slotTimeWindow: "10:30 AM - 12:00 PM",
    counterAssigned: "Counter 3",
    status: "CHECKED_IN",
    checkInTime: "10:40 AM",
    weighmentData: null,
    pfmsTxnId: null,
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: "KS-2026-454",
    tokenNumber: 48,
    farmerName: "Vikram Sharma",
    farmerMobile: "9988776655",
    farmerId: "PMK-HAR-77120",
    cropId: "chana",
    cropName: "Chana",
    quantityQuintal: 25,
    mandiId: "mandi-1",
    mandiName: "Karnal Central MSP Mandi",
    slotDate: new Date().toISOString().split("T")[0],
    slotTimeWindow: "12:00 PM - 01:30 PM",
    counterAssigned: null,
    status: "BOOKED",
    checkInTime: null,
    weighmentData: null,
    pfmsTxnId: null,
    createdAt: new Date().toISOString(),
  },
];

export let smsLogsState = [
  {
    id: "sms-1",
    timestamp: new Date(Date.now() - 3600000 * 3).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    recipient: "9876543210 (Ramesh Kumar)",
    message: "Kisan Setu: Payment of ₹91,000 for Token #45 (40 Qtl Wheat) credited to Bank A/c ending 4821 via PFMS. Ref: PFMS-99482019482.",
    type: "PAYMENT",
  },
  {
    id: "sms-2",
    timestamp: new Date(Date.now() - 3600000 * 2).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    recipient: "9812345678 (Gurpreet Singh)",
    message: "Kisan Setu: Weighment completed for Token #46. Net Quantity: 65 Quintals (FAQ Grade). Total Amount: ₹1,47,875. Payment processing via PFMS.",
    type: "WEIGHMENT",
  },
  {
    id: "sms-3",
    timestamp: new Date(Date.now() - 3600000 * 1).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    recipient: "9789012345 (Sukhwinder Kaur)",
    message: "Kisan Setu: Welcome to Karnal Mandi! Token #47 checked-in. Please proceed to Counter 3. Est. wait: 15 mins.",
    type: "GATE_ENTRY",
  },
];

export const addSmsLog = (recipientMobile, recipientName, message, type = 'INFO') => {
  const newLog = {
    id: "sms-" + Date.now(),
    timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    recipient: `${recipientMobile} (${recipientName})`,
    message,
    type,
  };
  smsLogsState = [newLog, ...smsLogsState];
  return newLog;
};
